[package]
name = "ec2_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.1"
aws-sdk-ec2 = "1.14"
chrono = "0.4.41"
ssh2 = "0.9"
tokio = { version = "1.0", features = ["full"] }
